"""Test Specification Models.

Shared Pydantic models for declarative test specifications generated by the
web-based test generators and consumed by the runner workflow builder.

Data flow: Web authors state machines + test specs -> saves to project / exports JSON -> Runner loads and builds workflows.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Union

from pydantic import BaseModel, Field


# =============================================================================
# Enums
# =============================================================================


class TestCategory(str, Enum):
    ELEMENT_PRESENCE = "element-presence"
    ACCESSIBILITY = "accessibility"
    FORM_VALIDATION = "form-validation"
    STATE_CONSISTENCY = "state-consistency"
    MODAL_DIALOG = "modal-dialog"
    NAVIGATION = "navigation"
    CROSS_PAGE_CONSISTENCY = "cross-page-consistency"
    CUSTOM = "custom"


class TestSeverity(str, Enum):
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class TriggerAction(str, Enum):
    CLICK = "click"
    TYPE = "type"
    HOVER = "hover"
    SCROLL = "scroll"
    CUSTOM = "custom"


class AssertionSource(str, Enum):
    AUTO = "auto"
    MANUAL = "manual"


class GeneratorType(str, Enum):
    SNAPSHOT = "snapshot"
    NAVIGATION = "navigation"


# =============================================================================
# Test Targets
# =============================================================================


class ElementIdTarget(BaseModel):
    type: Literal["elementId"] = "elementId"
    element_id: str = Field(alias="elementId")
    label: str | None = None

    model_config = {"populate_by_name": True}


class FormIdTarget(BaseModel):
    type: Literal["formId"] = "formId"
    form_id: str = Field(alias="formId")
    label: str | None = None

    model_config = {"populate_by_name": True}


class ModalIdTarget(BaseModel):
    type: Literal["modalId"] = "modalId"
    modal_id: str = Field(alias="modalId")
    label: str | None = None

    model_config = {"populate_by_name": True}


TestTarget = Union[ElementIdTarget, FormIdTarget, ModalIdTarget]


# =============================================================================
# Test Assertions
# =============================================================================


class TestAssertion(BaseModel):
    id: str
    description: str
    category: TestCategory
    severity: TestSeverity
    target: TestTarget = Field(discriminator="type")
    assertion_type: str = Field(alias="assertionType")
    expected: Any | None = None
    attribute_name: str | None = Field(default=None, alias="attributeName")
    source: AssertionSource
    reviewed: bool
    enabled: bool
    notes: str | None = None

    model_config = {"populate_by_name": True}


# =============================================================================
# Test Specifications
# =============================================================================


class TestSpecification(BaseModel):
    id: str
    name: str
    description: str
    category: TestCategory
    assertions: list[TestAssertion]
    state_id: str = Field(alias="stateId")
    transition_id: str | None = Field(default=None, alias="transitionId")
    source: AssertionSource
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")

    model_config = {"populate_by_name": True}


# =============================================================================
# Non-Visual State Machine
# =============================================================================


class NonVisualState(BaseModel):
    id: str
    name: str
    description: str
    element_ids: list[str] = Field(alias="elementIds")
    page_url: str | None = Field(default=None, alias="pageUrl")
    page_title: str | None = Field(default=None, alias="pageTitle")
    confidence: float

    model_config = {"populate_by_name": True}


class NonVisualTransition(BaseModel):
    id: str
    trigger_element_id: str = Field(alias="triggerElementId")
    trigger_label: str | None = Field(default=None, alias="triggerLabel")
    trigger_action: TriggerAction = Field(alias="triggerAction")
    from_state_id: str = Field(alias="fromStateId")
    to_state_id: str = Field(alias="toStateId")
    confidence: float

    model_config = {"populate_by_name": True}


# =============================================================================
# Metadata
# =============================================================================


class SnapshotMetadata(BaseModel):
    snapshot_id: str = Field(alias="snapshotId")
    page_url: str = Field(alias="pageUrl")
    page_title: str = Field(alias="pageTitle")
    captured_at: str = Field(alias="capturedAt")
    element_count: int = Field(alias="elementCount")
    form_count: int = Field(alias="formCount")
    modal_count: int = Field(alias="modalCount")

    model_config = {"populate_by_name": True}


class ExplorationMetadata(BaseModel):
    exploration_id: str = Field(alias="explorationId")
    target_url: str = Field(alias="targetUrl")
    states_discovered: int = Field(alias="statesDiscovered")
    transitions_discovered: int = Field(alias="transitionsDiscovered")
    explored_at: str = Field(alias="exploredAt")

    model_config = {"populate_by_name": True}


# =============================================================================
# Output format (JSON exchange between web and runner)
# =============================================================================


class TestGeneratorOutput(BaseModel):
    version: Literal["1.0.0"] = "1.0.0"
    project_id: str = Field(alias="projectId")
    generator_type: GeneratorType = Field(alias="generatorType")
    states: list[NonVisualState]
    transitions: list[NonVisualTransition]
    test_specifications: list[TestSpecification] = Field(alias="testSpecifications")
    snapshot_metadata: SnapshotMetadata | None = Field(
        default=None, alias="snapshotMetadata"
    )
    exploration_metadata: ExplorationMetadata | None = Field(
        default=None, alias="explorationMetadata"
    )
    created_at: str = Field(alias="createdAt")
    updated_at: str = Field(alias="updatedAt")

    model_config = {"populate_by_name": True}
