//! `qontinui-ci gen-workflow`: the hybrid-mode GitHub leg, generated from
//! `.qontinui/ci.toml`.
//!
//! Plan `2026-10-04-coord-managed-ci-for-every-tenant-with-an-actions-free-mode`,
//! D2 and Phase 8. In hybrid mode a repo's CI still runs on GitHub when no
//! local host takes the lease — but it runs the SAME executor over the SAME
//! manifest: every generated job is one `qontinui-ci run --job <name>` step.
//! Parity between the two lanes then holds by construction, not by review.
//!
//! * The only trigger is `workflow_dispatch`, with a `ref` input: coord
//!   dispatches the workflow for a commit; nothing else starts it (a `push` or
//!   `pull_request` trigger would spend Actions minutes the local lane exists
//!   to save).
//! * Scheduled manifest jobs are not generated: they run only on coord's
//!   schedule, and a dispatch is a gate run.
//! * The header marks the file GENERATED and records a content hash.
//! * The executor is installed from a pinned qontinui-schemas commit (a full
//!   sha, required): generation refuses a branch or a tag. `--check` takes the
//!   EXPECTED pin from its own `--executor-rev`, never from the committed
//!   file, so a hand-edited pin with a recomputed hash is still caught.
//!
//! # A hand-edit fails CI
//!
//! `qontinui-ci gen-workflow --check` exits non-zero when the committed file is
//! missing, is not a generated file, no longer matches its own recorded hash
//! (it was hand-edited), or differs from what the manifest generates now (it
//! is stale). A repo that commits the generated workflow wires that into its
//! own CI — in a `.qontinui/ci.toml` step, so both lanes run it:
//!
//! ```toml
//! [[jobs.steps]]
//! name = "generated workflow is current"
//! command = ["qontinui-ci", "gen-workflow", "--check", "--executor-rev", "<the pinned 40-hex sha>"]
//! ```
//!
//! or, in a GitHub workflow that still exists beside it:
//!
//! ```yaml
//! - name: The generated hybrid workflow is not hand-edited
//!   run: qontinui-ci gen-workflow --check --executor-rev <the pinned 40-hex sha>
//! ```
//!
//! (qontinui-schemas itself commits no generated workflow, so it wires
//! neither.)
//!
//! # Name collision
//!
//! `.github/workflows/qontinui-ci.yml` is also the name three repos already
//! use for a HAND-WRITTEN workflow (multistate, ui-bridge, qontinui-inspect at
//! the time this was written). Writing refuses to overwrite a file that does
//! not carry the GENERATED header unless `--force` is given; `--check` reports
//! such a file as "not generated" rather than as stale.

use sha2::{Digest, Sha256};

use crate::manifest::{CiManifest, Os, DEFAULT_STEP_TIMEOUT_SECS};

/// Where the generated workflow lives, repo-relative.
pub const WORKFLOW_PATH: &str = ".github/workflows/qontinui-ci.yml";

/// The first line of every generated file.
pub const GENERATED_MARKER: &str = "# GENERATED by `qontinui-ci gen-workflow`";

const HASH_PREFIX: &str = "# qontinui-ci-content-sha256: ";
const HASH_PLACEHOLDER: &str = "<computed>";

/// The pinned checkout action (the same pin qontinui's own workflows use).
const CHECKOUT_ACTION: &str = "actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0";

/// The repository the executor is installed from.
const EXECUTOR_REPO: &str = "https://github.com/qontinui/qontinui-schemas";

/// GitHub-hosted job ceiling, minutes.
const MAX_JOB_MINUTES: u64 = 360;

/// Provisioning headroom per job: installing the executor, tools, services.
const PROVISIONING_MINUTES: u64 = 30;

/// Generation inputs beyond the manifest.
#[derive(Debug, Clone)]
pub struct GenOptions {
    /// The manifest's repo-relative path (passed to `qontinui-ci run`).
    pub manifest_path: String,
    /// The qontinui-schemas commit the executor is installed from: a full
    /// 40-hex sha ([`pinned_rev`]). A branch or tag would let the GitHub leg
    /// run a different executor than the one the workflow was generated for.
    pub executor_rev: String,
}

fn runner_label(os: Os) -> &'static str {
    match os {
        Os::Any | Os::Linux => "ubuntu-latest",
        Os::Windows => "windows-latest",
        Os::Macos => "macos-latest",
    }
}

fn yaml_str(s: &str) -> String {
    // A double-quoted YAML scalar; manifest values never carry control
    // characters, but escape the two that matter anyway.
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn sha256_hex(text: &str) -> String {
    hex::encode(Sha256::digest(text.as_bytes()))
}

/// The hash a file records for itself: sha256 of the file with the hash
/// value replaced by a fixed placeholder.
fn content_hash(text: &str) -> Option<String> {
    let mut found = false;
    let normalized: String = text
        .split_inclusive('\n')
        .map(|line| {
            if line.starts_with(HASH_PREFIX) {
                found = true;
                format!("{HASH_PREFIX}{HASH_PLACEHOLDER}\n")
            } else {
                line.to_string()
            }
        })
        .collect();
    found.then(|| sha256_hex(&normalized))
}

fn recorded_hash(text: &str) -> Option<&str> {
    text.lines()
        .find_map(|l| l.strip_prefix(HASH_PREFIX))
        .map(str::trim)
}

/// Whether `text` is a generated workflow (by its first line).
pub fn is_generated(text: &str) -> bool {
    text.lines().next().is_some_and(|l| l.starts_with(GENERATED_MARKER))
}

/// Whether `s` is safe to write unquoted into the generated YAML and its
/// shell line: a plain repo-relative path or a commit-ish.
pub fn plain_token(s: &str) -> bool {
    !s.is_empty()
        && !s.starts_with('/')
        && !s.starts_with('-')
        && s.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '/'))
}

/// A full, lowercase 40-hex commit sha — the only executor pin accepted.
pub fn pinned_rev(s: &str) -> bool {
    s.len() == 40 && s.chars().all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c))
}

/// Generate the workflow for `manifest`.
pub fn generate(manifest: &CiManifest, opts: &GenOptions) -> String {
    let mut s = String::new();
    let scheduled: Vec<&str> = manifest
        .jobs
        .iter()
        .filter(|j| j.schedule.is_some())
        .map(|j| j.name.as_str())
        .collect();
    s.push_str(&format!(
        "{GENERATED_MARKER} from {} — DO NOT EDIT.\n",
        opts.manifest_path
    ));
    s.push_str(
        "#\n\
         # The GitHub leg of hybrid-mode coord-managed CI. Each job runs the same executor over\n\
         # the same manifest as a local CI node, so both lanes agree by construction (plan\n\
         # 2026-10-04-coord-managed-ci-for-every-tenant-with-an-actions-free-mode, D2). coord\n\
         # starts it with workflow_dispatch for one commit; it has no other trigger.\n\
         #\n",
    );
    s.push_str(&format!(
        "# To change it, edit {} and run `qontinui-ci gen-workflow`. A hand-edit\n\
         # fails `qontinui-ci gen-workflow --check`, which checks this file against the hash\n\
         # below and against a fresh generation.\n",
        opts.manifest_path
    ));
    s.push_str(&format!(
        "#\n# Scheduled manifest jobs are not part of the GitHub leg: {}.\n#\n",
        if scheduled.is_empty() {
            "none".to_string()
        } else {
            scheduled.join(", ")
        }
    ));
    s.push_str(&format!("{HASH_PREFIX}{HASH_PLACEHOLDER}\n\n"));
    s.push_str(
        "name: qontinui-ci\n\
         on:\n  \
           workflow_dispatch:\n    \
             inputs:\n      \
               ref:\n        \
                 description: \"The commit SHA (or ref) to run CI against\"\n        \
                 required: true\n        \
                 type: string\n\
         permissions:\n  \
           contents: read\n\
         jobs:\n",
    );
    let install = format!(
        "cargo install --locked --git {EXECUTOR_REPO} --rev {} qontinui-ci-exec --features import --bin qontinui-ci",
        opts.executor_rev
    );
    let mut first = true;
    for job in manifest.gate_jobs() {
        if !first {
            s.push('\n');
        }
        first = false;
        let limits_minutes: u64 = job
            .steps
            .iter()
            .map(|st| st.timeout_secs.unwrap_or(DEFAULT_STEP_TIMEOUT_SECS))
            .sum::<u64>()
            .div_ceil(60);
        let minutes = (limits_minutes + PROVISIONING_MINUTES).min(MAX_JOB_MINUTES);
        s.push_str(&format!("  {}:\n", job.name));
        let display = if job.os.len() > 1 {
            format!("{} / {} (${{{{ matrix.os }}}})", crate::manifest::CHECK_CONTEXT_PREFIX, job.name)
        } else {
            format!("{} / {}", crate::manifest::CHECK_CONTEXT_PREFIX, job.name)
        };
        s.push_str(&format!("    name: {}\n", yaml_str(&display)));
        if !job.needs.is_empty() {
            s.push_str(&format!("    needs: [{}]\n", job.needs.join(", ")));
        }
        if job.os.len() > 1 {
            // The display name carries the manifest OS, so each leg reports
            // exactly the check context the local lane does:
            // `qontinui-ci / <job> (<os>)` (CiJob::check_contexts).
            s.push_str("    strategy:\n      fail-fast: false\n      matrix:\n        include:\n");
            for o in &job.os {
                s.push_str(&format!(
                    "          - runner: {}\n            os: {}\n",
                    runner_label(*o),
                    o.as_str()
                ));
            }
            s.push_str("    runs-on: ${{ matrix.runner }}\n");
        } else {
            s.push_str(&format!(
                "    runs-on: {}\n",
                runner_label(job.os.first().copied().unwrap_or(Os::Any))
            ));
        }
        s.push_str(&format!("    timeout-minutes: {minutes}\n"));
        s.push_str("    steps:\n");
        s.push_str("      - name: Check out the dispatched ref\n");
        s.push_str(&format!("        uses: {CHECKOUT_ACTION}\n"));
        s.push_str(
            "        with:\n          \
               ref: ${{ inputs.ref }}\n          \
               path: ${{ github.event.repository.name }}\n          \
               fetch-depth: 0\n          \
               persist-credentials: false\n",
        );
        s.push_str("      - name: Install qontinui-ci\n        shell: bash\n");
        s.push_str(&format!("        run: {install}\n"));
        s.push_str(&format!(
            "      - name: {}\n",
            yaml_str(&format!("qontinui-ci run --job {}", job.name))
        ));
        s.push_str(
            "        shell: bash\n        \
               env:\n          \
                 GITHUB_TOKEN: ${{ github.token }}\n          \
                 QONTINUI_CI_REPO_DIR: ${{ github.workspace }}/${{ github.event.repository.name }}\n",
        );
        s.push_str(&format!(
            "        run: qontinui-ci run --job {} --repo-dir \"$QONTINUI_CI_REPO_DIR\" --root \"$GITHUB_WORKSPACE\" --manifest {}\n",
            job.name, opts.manifest_path
        ));
    }
    if first {
        // Every job is scheduled: GitHub refuses a workflow with no jobs, so
        // say so in a job that fails loudly rather than emit an invalid file.
        s.push_str(
            "  no-gate-jobs:\n    \
               name: \"qontinui-ci / no gate jobs\"\n    \
               runs-on: ubuntu-latest\n    \
               steps:\n      \
                 - name: The manifest declares only scheduled jobs\n        \
                   run: |\n          \
                     echo \"every job in the manifest is scheduled; the GitHub leg has nothing to run\" >&2\n          \
                     exit 1\n",
        );
    }
    let hash = content_hash(&s).unwrap_or_default();
    s.replace(
        &format!("{HASH_PREFIX}{HASH_PLACEHOLDER}"),
        &format!("{HASH_PREFIX}{hash}"),
    )
}

/// The verdict of `gen-workflow --check`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckVerdict {
    UpToDate,
    Missing,
    /// The file exists but is not a generated file.
    NotGenerated,
    /// It no longer matches its own recorded hash.
    HandEdited,
    /// Intact, but the manifest now generates something else.
    Stale,
}

impl CheckVerdict {
    pub fn explain(self) -> &'static str {
        match self {
            CheckVerdict::UpToDate => "up to date",
            CheckVerdict::Missing => "missing — run `qontinui-ci gen-workflow`",
            CheckVerdict::NotGenerated => {
                "not a generated file (no GENERATED header) — it is hand-written; rename it or \
                 replace it with `qontinui-ci gen-workflow --force`"
            }
            CheckVerdict::HandEdited => {
                "hand-edited — it no longer matches its recorded content hash; edit the manifest \
                 and run `qontinui-ci gen-workflow` instead"
            }
            CheckVerdict::Stale => {
                "stale — the manifest now generates a different workflow; run \
                 `qontinui-ci gen-workflow`"
            }
        }
    }
}

/// Compare a committed file (if any) against what would be generated.
pub fn check(existing: Option<&str>, expected: &str) -> CheckVerdict {
    let Some(existing) = existing else {
        return CheckVerdict::Missing;
    };
    let existing = existing.replace("\r\n", "\n");
    if !is_generated(&existing) {
        return CheckVerdict::NotGenerated;
    }
    match (recorded_hash(&existing), content_hash(&existing)) {
        (Some(recorded), Some(actual)) if recorded == actual => {}
        _ => return CheckVerdict::HandEdited,
    }
    if existing == expected {
        CheckVerdict::UpToDate
    } else {
        CheckVerdict::Stale
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const V2: &str = r#"
version = 2

[[jobs]]
name = "lint"
[[jobs.steps]]
name = "clippy"
command = ["cargo", "clippy"]
timeout_secs = 600

[[jobs]]
name = "test"
os = ["linux", "windows"]
needs = ["lint"]
[[jobs.steps]]
name = "test"
command = ["cargo", "test"]

[[jobs]]
name = "nightly"
schedule = "0 3 * * *"
[[jobs.steps]]
name = "slow"
command = ["cargo", "test", "--", "--ignored"]
"#;

    fn opts() -> GenOptions {
        GenOptions {
            manifest_path: ".qontinui/ci.toml".to_string(),
            executor_rev: REV.to_string(),
        }
    }

    const REV: &str = "84b13b0de3dd322f48e9f472a84c9ba490e88a3d";

    #[test]
    fn one_job_per_gate_job_dispatch_only() {
        let m = crate::manifest::parse_and_validate(V2).unwrap();
        let text = generate(&m, &opts());
        assert!(is_generated(&text));
        let y: serde_yaml_ng::Value = serde_yaml_ng::from_str(&text).unwrap();
        let on = y.get("on").unwrap().as_mapping().unwrap();
        assert_eq!(on.len(), 1);
        assert!(on.contains_key("workflow_dispatch"));
        let jobs = y.get("jobs").unwrap().as_mapping().unwrap();
        assert_eq!(jobs.len(), 2, "the scheduled job is not generated");
        let test = jobs.get("test").unwrap();
        assert_eq!(test.get("name").unwrap().as_str(), Some("qontinui-ci / test (${{ matrix.os }})"));
        assert_eq!(test.get("runs-on").unwrap().as_str(), Some("${{ matrix.runner }}"));
        assert_eq!(
            jobs.get("lint").unwrap().get("name").unwrap().as_str(),
            Some("qontinui-ci / lint")
        );
        let steps = test.get("steps").unwrap().as_sequence().unwrap();
        let run = steps[2].get("run").unwrap().as_str().unwrap();
        assert!(run.starts_with("qontinui-ci run --job test "));
        assert!(text.contains("not part of the GitHub leg: nightly"));
        // lint: 600s of steps + 30 provisioning.
        assert_eq!(
            jobs.get("lint").unwrap().get("timeout-minutes").unwrap().as_u64(),
            Some(40)
        );
    }

    #[test]
    fn check_tells_the_four_failures_apart() {
        let m = crate::manifest::parse_and_validate(V2).unwrap();
        let text = generate(&m, &opts());
        assert_eq!(check(Some(&text), &text), CheckVerdict::UpToDate);
        assert_eq!(check(Some(&text.replace('\n', "\r\n")), &text), CheckVerdict::UpToDate);
        assert_eq!(check(None, &text), CheckVerdict::Missing);
        assert_eq!(check(Some("name: hand\non: push\n"), &text), CheckVerdict::NotGenerated);
        let edited = text.replace("timeout-minutes: 40", "timeout-minutes: 41");
        assert_eq!(check(Some(&edited), &text), CheckVerdict::HandEdited);
        let other = generate(
            &m,
            &GenOptions {
                manifest_path: ".qontinui/ci.toml".into(),
                executor_rev: "0123456789abcdef0123456789abcdef01234567".into(),
            },
        );
        assert_eq!(check(Some(&other), &text), CheckVerdict::Stale);
        // A hand-edited pin with a recomputed hash is still stale against the
        // expected pin.
        let forged = {
            let swapped = text.replace(REV, "0123456789abcdef0123456789abcdef01234567");
            let h = content_hash(&swapped).unwrap();
            let old = recorded_hash(&swapped).unwrap().to_string();
            swapped.replace(&old, &h)
        };
        assert_eq!(check(Some(&forged), &text), CheckVerdict::Stale);
        assert!(pinned_rev(REV));
        assert!(!pinned_rev("main"));
        assert!(!pinned_rev("v1.0.0"));
        assert!(plain_token(".qontinui/ci.toml"));
        assert!(!plain_token("my ci.toml"));
        assert!(!plain_token("/abs/ci.toml"));
    }
}
