//! Prints the render fixtures that pin every non-Rust mirror of
//! [`Refusal::render`] — plan
//! `2026-09-20-the-published-product-works-without-knowing-a-development-environment-exists`,
//! Phase D3.
//!
//! A reader in another language (the web frontend's `lib/errors/refusal.ts`)
//! reproduces the render table so a refusal renders with no request. That
//! copy is pinned by a JSON dump of what THIS implementation renders over
//! every next-action kind × target × delay shape and every code ×
//! discriminator. Regenerate the dump whenever a table here changes:
//!
//! ```text
//! cargo run -q -p qontinui-types --example refusal_render_fixtures > refusal.render-fixtures.json
//! ```
//!
//! The targets include control characters, U+0085, U+3000 and U+FEFF, which
//! pin the exact whitespace and control-character sets `quotable` uses.

use qontinui_types::refusal::{NextAction, NextActionKind, Refusal, RefusalCode, RefusalSource};
use serde_json::json;

const AT: &str = "2026-09-29T00:00:00Z";

fn main() {
    let targets: [Option<&str>; 6] = [
        None,
        Some(""),
        Some("workspace_root"),
        Some("a\n\"b\"\t c\u{0085}d\u{3000}e\u{feff}f"),
        Some("  "),
        Some("https://example.com/settings"),
    ];
    let delays: [Option<u32>; 11] = [
        None,
        Some(0),
        Some(1),
        Some(45),
        Some(119),
        Some(120),
        Some(121),
        Some(7199),
        Some(7200),
        Some(172_800),
        Some(172_801),
    ];
    let kinds = NextActionKind::ALL
        .iter()
        .copied()
        .chain([NextActionKind::Unrecognised]);

    let mut next_action = Vec::new();
    for kind in kinds {
        for target in targets {
            for delay in delays {
                // The delay only renders for `retry_later`; one delayed shape
                // per other kind proves it is ignored there.
                if kind != NextActionKind::RetryLater && delay.is_some() && delay != Some(45) {
                    continue;
                }
                let mut na = NextAction::new(kind);
                na.target = target.map(str::to_string);
                na.retry_after_s = delay;
                next_action.push(json!({
                    "kind": kind.as_str(),
                    "target": target,
                    "retry_after_s": delay,
                    "render": na.render(),
                }));
            }
        }
    }

    let mut refusal = Vec::new();
    for &code in RefusalCode::ALL {
        for disc in [None, Some(""), Some("backend"), Some("a\nb \"c\"")] {
            let mut r = Refusal::new(
                code,
                NextAction::new(NextActionKind::SetSetting).with_target("workspace_root"),
                RefusalSource::Runner,
                AT,
            );
            r.discriminator = disc.map(str::to_string);
            refusal.push(json!({ "refusal": r, "render": r.render() }));
        }
    }

    let out = json!({
        "_source": "Generated by qontinui-schemas `cargo run -q -p qontinui-types --example refusal_render_fixtures` (NextAction::render and Refusal::render over every kind x target x delay shape and every code x discriminator). Regenerate whenever the Rust render tables change; never edit by hand.",
        "next_action": next_action,
        "refusal": refusal,
    });
    println!(
        "{}",
        serde_json::to_string_pretty(&out).expect("fixtures serialise")
    );
}
